author_id = "tinyrogue"
app_id = "tinyrogue-hello"
author_name = "tinyrogue"
app_name = "Hello Demo"

[files]
floor = { path = "forest.png" }
wall = { path = "tree.png" }
player = { path = "gopher.png" }
