author_id = "tinyrogue"
app_id = "tinyrogue-hello"
author_name = "tinyrogue"
app_name = "Hello Gopher"

[files]
floor = { path = "floor.png" }
wall = { path = "wall.png" }
player = { path = "gopher.png" }
