author_id = "tinyrogue"
app_id = "tinyrogue-hello"
author_name = "tinyrogue"
app_name = "Hello Gopher"

[files]
forest = { path = "forest.png" }
forest2 = { path = "forest2.png" }
tree = { path = "tree.png" }
tree2 = { path = "tree2.png" }
player = { path = "gopher.png" }
